name: mr_x_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.1 
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  http: ^1.2.1
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.5
  firebase_storage: ^11.7.7
  firebase_messaging: ^14.7.0
  firebase_app_check: ^0.2.2+7
  image_picker: ^1.1.2
  geolocator: ^9.0.2
  provider: ^6.1.1
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  location: ^5.0.3
  google_sign_in: ^5.4.0

dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_icons:
  android: true
  ios: true
  image_path: "lib/assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/GoogleLogo.png
    - lib/assets/map_background.jpg
    - lib/assets/map_background1.jpg
    - lib/assets/map_background2.jpg
    - lib/assets/map_background3.jpg
    - lib/assets/map-background4.png
    - lib/assets/map_background5.png
